### ISSUE TITLE
Blocker: The UI crashes on the following scenario

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#105]
**Steps:**

1. Click on 3 dots and click on late fee option. Play around the pop-up, and then click outside the modal
2. then click on 3 dots again.
3. The screen crashes.

Pre-requisites:
need 1 hourly staff and 1 monthly.

Login to the account: Phone: 4444444440
biz name: Hazel's dhaba

https://drive.google.com/file/d/1IRWk82FdndmCqIPo8QDPDz3wYnI4iyA6/view?usp=drivesdk

**Comment by HazelColaco19** [comment]
Still crashes
![image](https://user-images.githubusercontent.com/55691499/99073388-d1089c00-25db-11eb-8e9f-8c0ea17972c9.png)

**Comment by ShubhamModi004** [comment]
Checked it and will recheck

**Comment by HazelColaco19** [comment]
Does not occur. Can be closed
