### ISSUE TITLE
Shift duration animation is too slow for time Selector.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#11]
Shift duration animation is too slow for time Selector.
Description:-The time selection process is too slow and so a value=1 is added by default if the  save button is clicked without the animation coming to halt.

**Comment by ShubhamModi004** [comment]
I have not found a solution for this yet will look into it.

**Comment by ShubhamModi004** [comment]
This was opened long back and an alternate solution has already been implemented to resolve the issue caused by slower shift duration animation. 
Have no solution for it since the library I used doesn't provide ability to change the speed of scroll

**Comment by HazelColaco19** [comment]
This looks fixed when you scroll from 1 to 23, the button Save remains disabled.
However when you scroll back from 23 to 1, the button save remains enabled and if you click on it, by default it picks 23.

Apply the changes - disable the button if the animation is on the move, in both orders ( 1 to 23 and 23 to 1 )

@ShubhamModi004

**Comment by HazelColaco19** [comment]
Fixed

**Comment by HazelColaco19** [comment]
This is a rare case and doesn't have negative implication on app usage. Hence closing this
