### ISSUE TITLE
Issue with adding a number to Staff from ' Add to Contacts " option

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#110]
Issue:

The first digit gets cropped when it takes the number from the phone directory

![image](https://user-images.githubusercontent.com/55691499/99068368-6868f180-25d2-11eb-9e71-eddfcb6d7929.png)
![image](https://user-images.githubusercontent.com/55691499/99068421-820a3900-25d2-11eb-94b5-2c921a4a1aeb.png)

**Comment by ShubhamModi004** [comment]
This was discussed earlier we don't have a permanent fix for the number.

**Comment by HazelColaco19** [comment]
@sharangsamonkar This is a high priority issue. Can we do something about it?

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 
The spaces, brackets and dashes need to be removed and then the last 10 digits need to be taken.

**Comment by HazelColaco19** [comment]
@ShubhamModi004  
1. Add from contact fails to work if the number was saved with spaces, brackets, dashes

**Comment by HazelColaco19** [comment]
Fixed for all cases when you add staff to the business. Need to check the same while inviting admins

**Comment by HazelColaco19** [comment]
fixed on invite admin as well. closing ticket
