### ISSUE TITLE
The finish button and the header should be pushed towards the 3 dots as in design. current one is too close to start button

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#112]
design:

![image](https://user-images.githubusercontent.com/55691499/99069511-7e77b180-25d4-11eb-9ef5-b4cd7486e7d7.png)

developed:

![image](https://user-images.githubusercontent.com/55691499/99069435-5c7e2f00-25d4-11eb-8861-b24e4d49c3a4.png)

**Comment by HazelColaco19** [comment]
This is not fixed @ShubhamModi004 @sharangsamonkar 

![image](https://user-images.githubusercontent.com/55691499/99508809-04b43f00-29ab-11eb-8e5b-c4d5623be8d9.png)

**Comment by HazelColaco19** [comment]
Still not fixed. Can you check again @ShubhamModi004 

![image](https://user-images.githubusercontent.com/55691499/99635098-836eb200-2a67-11eb-8306-56cd05dab043.png)

**Comment by HazelColaco19** [comment]
@ShubhamModi004 lets get on a call to fix this. currently, the 3 dots in hourly staff have moved to the extreme right due to the change above.

**Comment by ShubhamModi004** [comment]
<img width="416" alt="Screenshot 2020-12-08 at 1 25 34 AM" src="https://user-images.githubusercontent.com/34206153/101398558-470ad500-38f4-11eb-8066-4e2c1762a73a.png">
<img width="481" alt="Screenshot 2020-12-08 at 1 25 45 AM" src="https://user-images.githubusercontent.com/34206153/101398568-4c681f80-38f4-11eb-9bc3-73bfa2743ba5.png">


Let me know if these screenshots are idea.
Considering it should look responsive across all devices

**Comment by HazelColaco19** [comment]
This one looks good. Please update. @ShubhamModi004 

<img width="416" alt="Screenshot 2020-12-08 at 1 25 34 AM" src="https://user-images.githubusercontent.com/34206153/101398558-470ad500-38f4-11eb-8066-4e2c1762a73a.png">

**Comment by HazelColaco19** [comment]
Fixed
