### ISSUE TITLE
We can see the hours spent by hourly staff even if the punch in is not done

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#114]
**Case:**

1. Set the start time and end time
2. Then delete both these times
3. The calculation is retained, the number of hours spent

![image](https://user-images.githubusercontent.com/55691499/99074612-14fca080-25de-11eb-8b5d-6cb259883ab0.png)

**Comment by ShubhamModi004** [comment]
Checked It and will recheck

**Comment by HazelColaco19** [comment]
fixed. However now if we delete the end time even start time is deleted. @sharangsamonkar need to discuss internally, but closing above thread
