### ISSUE TITLE
Splash screen breaks for smaller screen devices.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#12]
Splash screen breaks for smaller screen devices 
Description:-i tested this case from Nexus and the splash screen breaks for screen resolution 768x1280 pixel
https://lh3.googleusercontent.com/-FJWUTAyW9wg/X5lrOFY-UpI/AAAAAAAAAEc/WBlLZR8N2zcyVJb214bUounOrQav5kHKgCK8BGAsYHg/s0/6458063692904115058%253Faccount_id%253D25s.

**Comment by SumeshAj** [comment]
![2550909357332478065](https://user-images.githubusercontent.com/72379338/97833949-a0338780-1cfc-11eb-8047-bc2d3f1fddfa.jpg)

**Comment by ShubhamModi004** [comment]
I have been testing on a 4.7 inch screen emulator not facing the same issue. Ill try to reproduce same bug and fix

**Comment by HazelColaco19** [comment]
Tested and fixed. Does not happen on Nexus and Mi anymore.
