### ISSUE TITLE
Invite admin does not reflect in Business admin section

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#120]
**Scenario:**

1. The first time an admin was invited, the name was populated in the list.
2. Post " decline " of this invite, and sending another invite. The list does not populate

The list is visible in invited admins account post accept

![image](https://user-images.githubusercontent.com/55691499/99267929-8fc9f380-284a-11eb-9cdc-83905264f6b0.png)

Main owners account

![image](https://user-images.githubusercontent.com/55691499/99266717-15e53a80-2849-11eb-9937-7cb6a091fc58.png)

**Comment by HazelColaco19** [comment]
This is not fixed. The second invite is still not showing up in the list. Needs reboot @ShubhamModi004 @sharangsamonkar

**Comment by HazelColaco19** [comment]
This is still not working for the 2nd, 3rd invite onwards. You need a reboot to proceed. Check video: @ShubhamModi004 

https://drive.google.com/file/d/1NdugJLRjNhqtTGiU_qjWw6oal1ILNojV/view?usp=drivesdk

**Comment by ShubhamModi004** [comment]
This wasn't sent in the build .

**Comment by ShubhamModi004** [comment]
<img width="703" alt="Screenshot 2020-11-19 at 1 54 00 PM" src="https://user-images.githubusercontent.com/34206153/99640276-ae103900-2a6e-11eb-90b9-b5e3968d898f.png">

**Comment by HazelColaco19** [comment]
Fixed
