### ISSUE TITLE
Admin account: Issue with display of current days attendance on Single staff attendance page. attendance is not visible in record

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#122]

**Comment by ShubhamModi004** [comment]
I think something related to backend issue.

**Comment by HazelColaco19** [comment]
Attendance is now visible, however, when you change the attendance of the current date and go to the detailed page, it's not reflecting. @sharangsamonkar  
https://drive.google.com/file/d/1R4oNldAnZh-qgGOFqZ30UE3v-LNq77Vt/view?usp=drivesdk

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 Is the single staff page not loaded every time we go in?

**Comment by HazelColaco19** [comment]
Additional info, @sharangsamonkar 

if I exit and come back to the app, the record I marked as absent disappears and defaults to " present ".

Checked overtime, late fine, paid leave, half day. These modules behave correctly. Issue around logging " Absent "

**Comment by ShubhamModi004** [comment]
it is loaded every time we enter in add staff page.

**Comment by HazelColaco19** [comment]
fixed
