### ISSUE TITLE
The buttons in all the modals is not vertically aligned to the line and the bottom edge

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#124]
Instances repeat on Overtime modal, Edit Late fine, Set Alarm, Add time for hourly staff

The buttons are unequally spaced in the vertical space

**Example:**

![image](https://user-images.githubusercontent.com/55691499/99410375-6aa3b680-2918-11eb-98b7-de826f161d5b.png)

![image](https://user-images.githubusercontent.com/55691499/99410777-ddad2d00-2918-11eb-8477-d3c813ed87c2.png)

![image](https://user-images.githubusercontent.com/55691499/99410800-e43ba480-2918-11eb-84b2-fe59155ea3d8.png)

![image](https://user-images.githubusercontent.com/55691499/99410817-e9005880-2918-11eb-88eb-ae630ddb7356.png)

**Comment by sharangsamonkar** [comment]
1. When modal opens there should be no nav bar.
2. Spacing above and below the button needs to be the same.

**Comment by HazelColaco19** [comment]
Point 2 is not fixed for any modals @ShubhamModi004

**Comment by HazelColaco19** [comment]
point 2 is fixed, but spacing doesn't match the design. We need to add more space. @ShubhamModi004

**Comment by ShubhamModi004** [comment]
Will discuss over call to do finish this

**Comment by HazelColaco19** [comment]
fixed
