### ISSUE TITLE
Set Alarm: increase the width of the content box

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#126]
Design:

![image](https://user-images.githubusercontent.com/55691499/99412482-c66f3f00-291a-11eb-8707-04f50d338a93.png)

Developed: 
![image](https://user-images.githubusercontent.com/55691499/99412002-434de900-291a-11eb-88a8-2af339380b61.png)

**Comment by HazelColaco19** [comment]
The modal looks larger than before. Please check, these are the following issues:

1. Modal is larger than expected. Height of all modals seems to have boosted for some reason. Please check.
2. The description text is coming under the " Trash icon "
3. Distance between the Set Alarm and description is a lot


![image](https://user-images.githubusercontent.com/55691499/99654354-33e8b000-2a80-11eb-9a49-31d3fc332880.png)

**Comment by ShubhamModi004** [comment]
<img width="837" alt="Screenshot 2020-11-20 at 8 52 49 AM" src="https://user-images.githubusercontent.com/34206153/99754137-c6836080-2b0d-11eb-9035-bd0688998d53.png">
 
Or point 2 shud I be resolving?

**Comment by HazelColaco19** [comment]
fixed
