### ISSUE TITLE
Set alarm: If we click on the Notification and go to the app, the alarm keeps vibrating. The alarm should go off in such a case. This wasnt the case before

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#128]

**Comment by HazelColaco19** [comment]
not fixed

**Comment by HazelColaco19** [comment]
Not fixed. @ShubhamModi004 @sharangsamonkar Can you please discuss.

**Comment by ShubhamModi004** [comment]
There are two conditions, you kill the app and then click on the alarm the expected behaviour works.
If the app is in background you click on notification it doesn't pushed added the changes to fix the background notification fix.

**Comment by HazelColaco19** [comment]
@ShubhamModi004  #128, I tested 1 case, wanted to test the other case by deleting the alarm and setting a new one but the alarm is not ringing. does it ring just once a day? If that's the case, we should refresh and check if a new timing has been updated when an edit Is done on the alarm

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Also, I had tested for the case when the app is open in the background. it is still not fixed, can we discuss on your comment? My phone keeps vibrating when I reach inside the app and stops only when I kill it

**Comment by HazelColaco19** [comment]
The alarm doesn't ring at all anymore. @ShubhamModi004 @sharangsamonkar 

Tried setting an alarm and killing the app.
Tried setting an alarm and closing the app/ running in background
Tried setting an alarm and keeping it open on screen.

**Comment by HazelColaco19** [comment]
fixed
