### ISSUE TITLE
On removal of an admin, if you close the app on admins phone and open again, it loads with current organization data prepopulated in the business page

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#137]
Note: I now have two organisations with the name " Hazel enterprises "

For confidentiality reasons, we cannot expose any data of the company that removed the admin.

![image](https://user-images.githubusercontent.com/55691499/99519779-4c8d9300-29b8-11eb-93a3-e67788c209b1.png)

**Comment by ShubhamModi004** [comment]
We'll need a flow for what happens when an admin is removed.

**Comment by HazelColaco19** [comment]
fixed
