### ISSUE TITLE
Decline invite modal: The description text should be larger on smaller phones. Currently too small to read. Also, the note should've been on next line

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#138]
Design:

![image](https://user-images.githubusercontent.com/55691499/99522160-4fd64e00-29bb-11eb-9e32-d04d66b999da.png)

developed"
![image](https://user-images.githubusercontent.com/55691499/99522195-59f84c80-29bb-11eb-9980-395eaed1af53.png)

**Comment by HazelColaco19** [comment]
The " Note " in the description should be on the second line. As mentioned in the bug ticket above

![image](https://user-images.githubusercontent.com/55691499/99656900-76f85280-2a83-11eb-9fee-4f885f7b2dcf.png)

**Comment by HazelColaco19** [comment]
The spacing between the title and paragraph needs to be respected. Currently its not matching. Was not the same before, check screenshot above

![image](https://user-images.githubusercontent.com/55691499/100869006-6bb11800-34c2-11eb-9fea-fdf06c3a86d7.png)

@ShubhamModi004

**Comment by ShubhamModi004** [comment]
Added a spacing of 5

**Comment by HazelColaco19** [comment]
fixed
