### ISSUE TITLE
Once the admin accepts the invite, its is not instantly updated on owners list. We have to restart the app to see the change

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#150]

**Comment by HazelColaco19** [comment]
@sharangsamonkar @ShubhamModi004 

please discuss

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 @HazelColaco19 
When you come back to the tab, you see the updated list.

**Comment by HazelColaco19** [comment]
When you come back to the tab, you see the updated list. ---> Its not working. Switched between tabs but doesn't reflect. you need to kill the app and start again.

@sharangsamonkar @ShubhamModi004

**Comment by ShubhamModi004** [comment]
Try moving between Screens

**Comment by HazelColaco19** [comment]
This is working, but it needs to be fast enough to avoid seeing the change. Can it be made faster? I can currently see the status change from invited to a member in the business screen @sharangsamonkar @ShubhamModi004

**Comment by sharangsamonkar** [comment]
need to discuss with @HazelColaco19

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 
Can you check this and update?

**Comment by ShubhamModi004** [comment]
Checked It is working perfectly shows a loader and removes the invited option, delay was for about a second on a 2g network.

**Comment by HazelColaco19** [comment]
fixed
