### ISSUE TITLE
Could not add Staff if the salary was an amount as big as this. See screenshot

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#151]
![image](https://user-images.githubusercontent.com/55691499/99666184-a2356e80-2a90-11eb-83b3-1f30044d4725.png)

![image](https://user-images.githubusercontent.com/55691499/99666198-a9f51300-2a90-11eb-81da-622e7477a06a.png)

**Comment by sharangsamonkar** [comment]
Number is too large to be stored in the DB. Do we really need to support numbers this big? What is the biggest number that would be a valid monthly salary?

**Comment by HazelColaco19** [comment]
The client will confirm and revert.

**Comment by HazelColaco19** [comment]
Maximum 12 digits should be handled @sharangsamonkar Is this already in place?

**Comment by sharangsamonkar** [comment]
yes

**Comment by HazelColaco19** [comment]
Closing this ticket
