### ISSUE TITLE
Can we disable the user from editing the " Payout date " ? Keeping the edit will lead to many linkages in calculations

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#157]

**Comment by HazelColaco19** [comment]
Fixed

**Comment by HazelColaco19** [comment]
The payout date can be edited for a weekly staff. @ShubhamModi004 reopening the issue

**Comment by ShubhamModi004** [comment]
@HazelColaco19 

A weekly staff doesn't have a payout date, he has a payout day. In case of edit already removed the edit option
<img width="426" alt="Screenshot 2020-12-13 at 1 59 45 PM" src="https://user-images.githubusercontent.com/34206153/102007026-7d5cb000-3d4b-11eb-8367-de6722180f6a.png">

**Comment by HazelColaco19** [comment]
fixed
