### ISSUE TITLE
Translate feature is not applied at certain areas. Find list below in description

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#158]
1.  Shift duration pop up: The HRs/ Mins is not converted

![image](https://user-images.githubusercontent.com/55691499/100332341-479f9380-2ff7-11eb-8095-b13d414e6da4.png)

2. Today from attendance landing is not converted
![image](https://user-images.githubusercontent.com/55691499/100332395-58500980-2ff7-11eb-92d1-35f12f7e0075.png)

3. On click of 3 dots (on both employee types ), the following is not converted:

a. Mark as Half Day
b. Mark as Paid Leave/ holiday
c. Add Overtime
d. Edit late fine
e. Edit note

4. On click of Add overtime above, we have " Overtime " modal without any provision for translation.

5. On click of Edit late fine modal, all of the elements would be translated

6. on click of Edit Note, the cancel button is not translated.

7. Business page: Under Business admins section, no translation for word " Owner, Invited "

8. Set Alarm Modal ( the title, description, Cancel set alarm button and AM/ PM )

**Comment by ShubhamModi004** [comment]
I don't think there is a translation for AM PM

**Comment by HazelColaco19** [comment]
fixed

**Comment by snehaajency** [comment]
Following things are not getting converted 
1.The title "business profile".
2.the owners name on business profile.
3.on business page the data under owners name,businessname,currency.,business admins.
4.profile>>about us>> the content below about us.

refer the images bellow:
![Screenshot_2021-01-11-15-55-33-760_com app ogaji test](https://user-images.githubusercontent.com/4660706/104170026-7e562f80-5426-11eb-9c39-3e9730f3f266.jpg)
![Screenshot_2021-01-11-16-01-51-192_com app ogaji test](https://user-images.githubusercontent.com/4660706/104170042-82824d00-5426-11eb-988a-f26c2634f23f.jpg)

**Comment by ShubhamModi004** [comment]
2.the owners name on business profile
> Not sure if we can translate a person's name.

3.on business page the data under owners name,businessname,currency.,business admins.
> Not sure if a person's name or company or currency or business admin's name should be translated.

7.On business page>>the location on top is not having a T.
> I doubt a country name's get translated to some other language.

**Comment by ShubhamModi004** [comment]
8. Can you provide screen shots for this point

**Comment by snehaajency** [comment]
@ShubhamModi004 
![Screenshot_2021-01-14-10-56-47-672_com app ogaji test](https://user-images.githubusercontent.com/4660706/104549140-41717f00-5658-11eb-8c00-f8843a15cea9.jpg)
![Screenshot_2021-01-14-10-56-39-082_com app ogaji test](https://user-images.githubusercontent.com/4660706/104549148-459d9c80-5658-11eb-8f17-6a16e03cb5c7.jpg)
![Screenshot_2021-01-14-10-57-33-963_com app ogaji test](https://user-images.githubusercontent.com/4660706/104549158-4b937d80-5658-11eb-8ec5-e9b4a1c3a147.jpg)
![Screenshot_2021-01-12-15-12-05-495_com app ogaji test](https://user-images.githubusercontent.com/4660706/104549196-5a7a3000-5658-11eb-84f4-5ac6fd4f87e3.jpg)

**Comment by snehaajency** [comment]
![Screenshot_2021-01-19-16-08-45-887_com app ogaji test](https://user-images.githubusercontent.com/4660706/105024060-aae6f880-5a71-11eb-8ef5-84664c5871e4.jpg)
![Screenshot_2021-01-19-16-10-54-984_com app ogaji test](https://user-images.githubusercontent.com/4660706/105024144-c0f4b900-5a71-11eb-81a9-c3b316209c65.jpg)
![Screenshot_2021-01-19-16-13-16-374_com app ogaji test](https://user-images.githubusercontent.com/4660706/105024225-d79b1000-5a71-11eb-8d94-84f00ab4a574.jpg)
![Screenshot_2021-01-19-16-13-32-480_com app ogaji test](https://user-images.githubusercontent.com/4660706/105024239-dcf85a80-5a71-11eb-8c05-6a1ce9236f9d.jpg)
![Screenshot_2021-01-19-16-13-25-742_com app ogaji test](https://user-images.githubusercontent.com/4660706/105024251-e255a500-5a71-11eb-8c6b-a062f42aaf89.jpg)
fixed 1,4,5,6,8
