### ISSUE TITLE
Why do we have an enabled delete button on overtime, late fine modals when there is no data filled inn?

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#159]
Current issue:

On deletion of the record which is not present, the app leaves a could not handle response

**Expected:**

User should see a delete button, but it should be disabled if 
a. it is a fresh delete request ( and not edit )

**Comment by HazelColaco19** [comment]
This is seen fixed, however now if we add overtime to a staff or a late fine or even delete the previous record we get an error.
See video: https://drive.google.com/file/d/1X1goOLArHc_Rqkbwpvh5resJcXFyFeI6/view?usp=drivesdk

@ShubhamModi004 @sharangsamonkar

**Comment by HazelColaco19** [comment]
fixed

**Comment by ShubhamModi004** [comment]
This was fixed in the first attempt, due to some changes in the backend. Error messages were getting thrown.
