### ISSUE TITLE
Start time doesn't function for hourly staff

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#16]
Description:- 
Start time doesn't function. The time Selected doesn't reflect in homepage and start button still appears Its better by default it shows the current timing for start time while selecting the time.

**Comment by SumeshAj** [comment]
How do I select  00:01 ?
Time selector must start from 00 instead of 01 and end at 23 and not 24.

**Comment by ShubhamModi004** [comment]
I had a discussion with Sharang to keep it as Hours and Minutes
