### ISSUE TITLE
The Add staff button should be shifted down ( check arrow ). Also, we should not see the grey box ( highlighted in blue box ). check design for both

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#165]
Design:

![image](https://user-images.githubusercontent.com/55691499/100611454-5fe51a80-3337-11eb-9695-e0971b2c54da.png)

Developed:
![image](https://user-images.githubusercontent.com/55691499/100611252-11378080-3337-11eb-9066-0800b0533ec4.png)

**Comment by ShubhamModi004** [comment]
Thought it was a part of the Hourly staff container

**Comment by HazelColaco19** [comment]
fixed
