### ISSUE TITLE
Created a Staff " G1| monthly ". Upon creation, staff is defaulted to " Paid leave " on staff landing page but can be seen present in attendance section

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#167]
Additional Info: The last action on the attendance page was marking " Hazel m1 " on paid leave. 

![image](https://user-images.githubusercontent.com/55691499/100612729-71c7bd00-3339-11eb-8aa9-aca35960f785.png)

![image](https://user-images.githubusercontent.com/55691499/100612748-75f3da80-3339-11eb-84c0-5fd199f93091.png)

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 Page doesnt referesh/ If i close the app and come then it works.

**Comment by ShubhamModi004** [comment]
Added the refresh on the page

**Comment by HazelColaco19** [comment]
fixed
