### ISSUE TITLE
Counter for attendance doesn't function.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#17]
Description:-The counter of present and absent shows wrong data.it keeps on adding the number of touches to its fields.

**Comment by SumeshAj** [comment]
![2020-11-01 (2)](https://user-images.githubusercontent.com/72379338/97835915-3d90ba80-1d01-11eb-9434-e74480b2794e.jpg)

**Comment by SumeshAj** [comment]
Attendance fails for days other than "Today".
![2020-11-03](https://user-images.githubusercontent.com/72379338/97988527-20441500-1e03-11eb-82ee-817dbc1b01a9.jpg)

**Comment by ShubhamModi004** [comment]
3rd November build

**Comment by SumeshAj** [comment]
Same issue exists The default value is taken as Zero and so -ve values are shown if marked absent..Even the marked attendance of previous days  doesnt show correct status..
eg.If i mark absent for previous day suppose 2nd nov and move to 3rd nov and move to "Today" when i traverse back to 2nd Nov i dont get the correct marked values.
