### ISSUE TITLE
You can view code in the employee profile screen. Also check the other fields. This happens on page load, first 5 seconds

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#171]
![image](https://user-images.githubusercontent.com/55691499/100623623-6a5be000-3348-11eb-9e60-ecf8e27c5a45.png)

**Comment by HazelColaco19** [comment]
Not fixed. @ShubhamModi004 logged in #217 and tracked here. Please check. Check for a Weekly staff

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 This issue has come up too many times. Same thing happens when you send a no_user code in the verifyOtp api.

Can you please check this and close it once and for all?

**Comment by ShubhamModi004** [comment]
This issue is a translation error if the key is not present at one screen for a type of text, this error appears not related to single file.
Fixed the one mentioned here .

**Comment by HazelColaco19** [comment]
This seems fixed but has opened up one more issue, looks like it needs a refresh. will open a new ticket. #239
