### ISSUE TITLE
Post doing the edits for Staff in issue 185, created a new staff. However that Staff got marked to " Absent " on Staff listing and the Staff I edited for got marked to present

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#186]
Case:

Edited and prepared data for Staff  in #185 

Current state: This staff is absent on dec 4 with expected salary value to be 4419.35.

On adding " besto monthly ", he gets marked to present only on Staff listing page - but is still shown absent on attendance listing page. 
The default salary calculation of besto monthly is correct - 3870.96. ( all 4 presents , sal month = 30k ).

![image](https://user-images.githubusercontent.com/55691499/101152101-988f3780-3648-11eb-8fb9-6575d7c96e2d.png)

![image](https://user-images.githubusercontent.com/55691499/101152122-9fb64580-3648-11eb-85a9-6b71d352f532.png)

**Comment by sharangsamonkar** [comment]
Works fine for me. Can you re-check and let me know?

**Comment by HazelColaco19** [comment]
fixed
