### ISSUE TITLE
Add previous month modal has a code variable. Please check

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#188]
![image](https://user-images.githubusercontent.com/55691499/101159517-88c92080-3653-11eb-8e8e-aac113d6a1dd.png)

**Comment by HazelColaco19** [comment]
The code is gone, but the alignment of the first pointer is incorrect

![image](https://user-images.githubusercontent.com/55691499/101322604-53a81280-388d-11eb-982f-9f53873bb019.png)

**Comment by ShubhamModi004** [comment]
center aligning the tick and text.
<img width="1049" alt="Screenshot 2020-12-08 at 1 14 59 AM" src="https://user-images.githubusercontent.com/34206153/101397516-cc8d8580-38f2-11eb-9ee4-80a05f2d886d.png">

**Comment by HazelColaco19** [comment]
fixed
