### ISSUE TITLE
On sTaff listing screen: The  payable number is incorrect if you have more than 1 month. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#190]
Case:
1. the payable value displayed is correct if its just one month.
2. if its two months ( nov + current ) the value is displayed as 30k, which is the staffs salary for nov. It shudv been 30k + payable of dec ( 3870 )

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 Salary is displayed instead of the amount due.

Same as #218

**Comment by ShubhamModi004** [comment]
Assuming it is similar to #218 so assigning to QA

**Comment by HazelColaco19** [comment]
fixed
