### ISSUE TITLE
Is this previous payroll date hardcoded? or is it one date prior to current payroll date? please check

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#197]
![image](https://user-images.githubusercontent.com/55691499/101173368-73122600-3668-11eb-8b08-f46e1824a3fe.png)

**Comment by sharangsamonkar** [comment]
It is one prior. Works fine for me. Can you replicate again and share the number?

**Comment by HazelColaco19** [comment]
Works fine. Closing this
