### ISSUE TITLE
The menu fluctuates and appears when we add a txn

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#199]

**Comment by sharangsamonkar** [comment]
@HazelColaco19 
Can you share a video for reference?

**Comment by HazelColaco19** [comment]
This issue is seen only on smaller end phones ( nexus ). Have recorded using One plus, the events on Nexus. Hence cannot upload due to the file size. Sent to @ShubhamModi004 on Whatsap

**Comment by HazelColaco19** [comment]
Closing this and keeping the duplicate open. #176
