### ISSUE TITLE
Working shift hours of staff is mentioned as shift hours of the business | Undefined hours issue

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#20]
Working shift hours of staff is mentioned as shift hours of the business in the attendance below their names.

**Comment by SumeshAj** [comment]
![2020-11-04 (1)](https://user-images.githubusercontent.com/72379338/98111991-71b5d800-1ec7-11eb-937c-09552a45e493.jpg)

**Comment by sharangsamonkar** [comment]
Issue has been fixed. "undefined" should not appear for work basis staff.

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 hours shown as undefined. " is passed in the api.

**Comment by HazelColaco19** [comment]
fixed
