### ISSUE TITLE
Comment for " payment taken " got saved as the comment saved for the previous transaction, " Payment given "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#207]
Issue: 

1. create a txn, type = payment given. add unique details
![image](https://user-images.githubusercontent.com/55691499/101182264-dd7c9380-3673-11eb-9ff0-c86464a01c18.png)

2. create a txn, type = payment taken. add unique details.
![image](https://user-images.githubusercontent.com/55691499/101182230-d35a9500-3673-11eb-8327-f7c4c9df6653.png)

3. come to txn listing page
4. you will see the note entered in step 1 repeats in step 2.

![image](https://user-images.githubusercontent.com/55691499/101181992-8ecef980-3673-11eb-83c7-6c0e87196c5a.png)

5. Kill the app and open again, the comment of 2 is seen displayed

![image](https://user-images.githubusercontent.com/55691499/101182468-216f9880-3674-11eb-8e2b-133483a47621.png)

**Comment by ShubhamModi004** [comment]
Assigning it to QA thinking issue might be related to someother issue and got resolved

**Comment by HazelColaco19** [comment]
Fixed
