### ISSUE TITLE
Pending dues were cleared but still we can see it is annotating clearance of pending dues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#209]
Expected:

Grey out and disable the **pending dues** button and labels if they are already cleared

![image](https://user-images.githubusercontent.com/55691499/101183448-8aa3db80-3675-11eb-9377-779ee08d27bc.png)

**Comment by sharangsamonkar** [comment]
Related to #210

**Comment by HazelColaco19** [comment]
fixed
