### ISSUE TITLE
 Allow the user to change the amount on the pending due txn, but once the amount is changed, update it in clear dues card

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#210]
If this above is not possible, then Freeze the amount and txn type on " add txn " screen, if the user has gotten to this screen by clicking on " Clear Dues " button

![image](https://user-images.githubusercontent.com/55691499/101184456-becbcc00-3676-11eb-992e-80e5cf63b625.png)

**Comment by HazelColaco19** [comment]
@ShubhamModi004 @sharangsamonkar 

If the txn has been paid in future month, which is equal or more than past month dues, then have the " Clear dues " button set to Grey. Txntype = dues paid

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 
1. handle disableClearDues
2. Due cleared needs to be changed to Dues paid in the translation.

**Comment by HazelColaco19** [comment]
fixed
