### ISSUE TITLE
Previous Payroll cycle 'To pay' is taken from salary, needs to be taken from amountDue

### ISSUE THREAD

**Issue by sharangsamonkar** [ajency/Dhanda-App#218]
![Screenshot_2020-12-06-11-22-35-46_251cb7a358685c9fab422048ceacf20a.jpg](https://user-images.githubusercontent.com/29853994/101272840-f1301300-37b5-11eb-8b7c-0d6514b35c27.jpg)

**Comment by HazelColaco19** [comment]
[https://github.com/ajency/Dhanda-App/issues/190](url)

**Comment by HazelColaco19** [comment]
Duplicate of #190

**Comment by HazelColaco19** [comment]
fixed
