### ISSUE TITLE
On edit transaction staff reference id is passed instead of transactions reference id | transaction type is not passed.

### ISSUE THREAD

**Issue by sharangsamonkar** [ajency/Dhanda-App#221]

**Comment by HazelColaco19** [comment]
The Transaction disappears from Txn listing screen post EDIT. Tried with Bonus and Allowance. Not fixed @ShubhamModi004 @sharangsamonkar

**Comment by HazelColaco19** [comment]
1. Transaction on click of Edit, you can only edit it for that day.

Use case: What if I had added it by mistake, and it was supposed to be on some other day?  An I want to change it via edit I cannot do it


2. The number on click disappears totally. Can we not have the previous number intact and only display the cursor so the user can edit?

See video for both: https://drive.google.com/file/d/1_cobkMTjtpKDJ-eRMaYT54O4Ur4m7UaG/view?usp=drivesdk

**Comment by HazelColaco19** [comment]
What has been fixed in this? Both the points are clearly not fixed. @ShubhamModi004

**Comment by HazelColaco19** [comment]
Point 1 - is still not fixed. @ShubhamModi004

**Comment by sharangsamonkar** [comment]
3. Cancel should not remove the date.

**Comment by sharangsamonkar** [comment]
cancel part on hold

**Comment by HazelColaco19** [comment]
Fixed. Any reason why cancel is on hold? @sharangsamonkar

**Comment by ShubhamModi004** [comment]
@sharangsamonkar 
### The body that I send incase of edit.
**Body passed** {"amount": "9000", "date": "2020-12-13", "description": "Description", "refId": "SIM581607836199484", "type": "deduction"}.

### Response I get on due breakup
**Transactions** [{"amount": 0, "date": "2020-12-13", "days": 3, "description": "", "hours": "", "rate": "", "refId": "", "transactionType": "present"}, {"amount": -9000, "date": "2020-12-13T00:00:00.000Z", "days": "", "description": "Description", "hours": "", "rate": "", "refId": "SIM581607836199484", "transactionType": "allowance"}]

**Comment by sharangsamonkar** [comment]
fixed. now on edit of the transaction the details are displayed correctly

**Comment by HazelColaco19** [comment]
On edit of the transaction, the record disappears from the list @sharangsamonkar

**Comment by HazelColaco19** [comment]
The transaction disappears since it gets saved to the current date. Issue marked to @ShubhamModi004 
Related issue: #281

**Comment by HazelColaco19** [comment]
Closing this
