### ISSUE TITLE
Besto monthly> Added a previous month > this months calendar is locked in attendance detailed screen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#223]
**Problem:**

Currently, It is very tedious to add a new attendance to a newly added month by individually clicking on " back " in the attendance listing screen.  

**Expected:**

When a new month is created, can we have the list appear in the detailed view of attendance so that it is very easy for an admin to mark his attendance records in one go?

_Case:_

Created October in staffs payroll, tried adding records but I have to traverse back 30 days of November and 7 days of December to be able to do so. which is incorrect and tedious. Can we have all the dates appear per added payroll in the below screen?

![image](https://user-images.githubusercontent.com/55691499/101325234-6cb2c280-3891-11eb-8649-254bc8092ad6.png)

**Comment by sharangsamonkar** [comment]
need to check with a new user.

**Comment by HazelColaco19** [comment]
fixed
