### ISSUE TITLE
Deduction Record is no longer shown in red. All minuses are shown in green now. ( late fine/ loan )

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#225]
![image](https://user-images.githubusercontent.com/55691499/101328142-a5549b00-3895-11eb-92f3-85168f38e72b.png)

**Comment by HazelColaco19** [comment]
@sharangsamonkar  Only the recent debit is shown in red, else the colour goes to green. See all other examples in list


![image](https://user-images.githubusercontent.com/55691499/101361130-9a652f00-38c4-11eb-94f2-1314a9fa816d.png)

**Comment by sharangsamonkar** [comment]
showing up properly for me.

@ShubhamModi004 is this some to do with the data not refreshing?

**Comment by ShubhamModi004** [comment]
showing up properly for me as well followed the same steps.
I think issue was related to some other issue and got resolved.

**Comment by HazelColaco19** [comment]
fixed
