### ISSUE TITLE
Attendance listing: On click of " Start ", and then adding a time - when user clicks on " Finish " and deletes the value from " Finish ", even the start value is deleted

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#228]
NOTE: This issue was reported earlier.

![image](https://user-images.githubusercontent.com/55691499/101352490-3b012200-38b8-11eb-9256-ea00652222fa.png)

Entered Start time
![image](https://user-images.githubusercontent.com/55691499/101352547-53713c80-38b8-11eb-84d9-9633c5279ebf.png)

Clicked on finish time, but clicked on delete instead of save
![image](https://user-images.githubusercontent.com/55691499/101352511-45232080-38b8-11eb-8cb0-5b62c0a46b19.png)

Even start time gets deleted
![image](https://user-images.githubusercontent.com/55691499/101352641-7ac80980-38b8-11eb-8622-578786144b9b.png)

**Comment by ShubhamModi004** [comment]
Already discussed on this .

**Comment by ShubhamModi004** [comment]
Discussion: On removal of finish time keep the start Time and on removal of start time delete both.

**Comment by HazelColaco19** [comment]
fixed
