### ISSUE TITLE
Hourly staff: Time shouldv been populated if there is a punch in, if there is no punch in then absent.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#229]
![image](https://user-images.githubusercontent.com/55691499/101354969-f4adc200-38bb-11eb-82d0-9a17d5c7ff1d.png)

_Reference #163_

**Comment by ShubhamModi004** [comment]
Already discussed.

**Comment by ShubhamModi004** [comment]
We discussed to show status as Absent if hours not present. 
I don't have the punch in and punch out time at the staff screen.

**Comment by HazelColaco19** [comment]
Fixed
