### ISSUE TITLE
Half days are shown cumulated under current date, there should have been two records

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#232]
Expected: Every half day should have a separate record

Case:

7th dec, 8th dec were both marked on half days

![image](https://user-images.githubusercontent.com/55691499/101377068-65160c80-38d7-11eb-82d2-53248d3cf421.png)

in staff txn detail screen, the half day is shown cumulated in one record with 8th dec as the date

![image](https://user-images.githubusercontent.com/55691499/101377139-76f7af80-38d7-11eb-96f1-26eaf31ca7d6.png)

**Comment by HazelColaco19** [comment]
not fixed. added two half days on two different days and it got added to the latest date out of the two.

![image](https://user-images.githubusercontent.com/55691499/101496696-14161f00-3990-11eb-8643-f05ec8bb0f77.png)


![image](https://user-images.githubusercontent.com/55691499/101496719-1aa49680-3990-11eb-8a45-872bed9f60f2.png)

**Comment by sharangsamonkar** [comment]
All statues are clubbed into one.

**Comment by HazelColaco19** [comment]
Also, this way it gives us a brief up on the total number of Half days taken etc.
