### ISSUE TITLE
The value amounted to " Current dues payable from 1 dec " is incorrect

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#236]
Reference #189 

Monthly salary = 30k
1-day salary = 1k

**Expected:**

Monthly Advance should have been Earned = Half Day + present + paid leave + OT - LT - OB - LT =  3700

So this payable value is start date of payroll cycle up till current date.  So we have 8 days only ( changed date settings for testing )

![image](https://user-images.githubusercontent.com/55691499/101380123-24b88d80-38db-11eb-924d-214322951edb.png)

**Comment by ShubhamModi004** [comment]
Added a refresh to fetch new amount

**Comment by HazelColaco19** [comment]
Fixed
