### ISSUE TITLE
Miscalculation of salary

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#237]
Settings:

salary = 30k
Business month cal = every month, 30 days

1. Calculates wrongly on No dues card
2. calculation incorrect inside the txn listing card.

![image](https://user-images.githubusercontent.com/55691499/101380912-233b9500-38dc-11eb-93c6-37aabe918963.png)

![image](https://user-images.githubusercontent.com/55691499/101380988-39495580-38dc-11eb-8687-048b39603bab.png)

![image](https://user-images.githubusercontent.com/55691499/101381045-45351780-38dc-11eb-870e-a7e5a730888b.png)

**Comment by sharangsamonkar** [comment]
Staff: Monthly advance.

**Comment by HazelColaco19** [comment]
Will revert on this

**Comment by HazelColaco19** [comment]
Basically we dont need the second option - 30 days anymore. We can keep it for future release, if client requests ... but after thorough research.
So we default
- monthly calculation to monthly calendar
- business shift to 8 hours

**Comment by sharangsamonkar** [comment]
defaulting to calendar month for salary calculation done on the backend.

@ShubhamModi004 Please assign to qa once the ui changes are done.

**Comment by HazelColaco19** [comment]
fixed
