### ISSUE TITLE
Currency needs to be in the message | There are no messages sent on click of the alert after creation of a txn

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#238]
**Expected flow:**

After the creation of the transaction, on click of the toast, the admin should be able t choose the Whatsapp number to send the message to.

Message format: 

< txn type >  has been added on < dd/mm/yyyy > of < currency/amount > to your payroll

**Comment by HazelColaco19** [comment]
Incorrect message format applied on sharing of transaction. This is clearly incorrect and should have been checked.  See the expected format above please @sharangsamonkar @ShubhamModi004 . This transaction was " allowance ". But this happens for all transactions.

" Thas been added on We/32/2020 Tof 12458 Tto your payroll "

![image](https://user-images.githubusercontent.com/55691499/101649201-a259d600-3a60-11eb-886e-a1718ae2f669.png)

**Comment by HazelColaco19** [comment]
This issue still exists on all the txn types. @ShubhamModi004

**Comment by sharangsamonkar** [comment]
fixed in 11 dec 3.55 build

**Comment by sharangsamonkar** [comment]
Add a currency in the message

**Comment by HazelColaco19** [comment]
fixed
