### ISSUE TITLE
Hourly staff, salary calculation is incorrect

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#245]
![image](https://user-images.githubusercontent.com/55691499/101506108-0dd97000-399b-11eb-935b-adbffee88a84.png)

**Comment by HazelColaco19** [comment]
The calculation is shown correctly on dues screen, but incorrectly displayed in txn listing screen. current payable value
![image](https://user-images.githubusercontent.com/55691499/101790055-05fb0680-3b28-11eb-9305-44ceb9963fa4.png)

![image](https://user-images.githubusercontent.com/55691499/101790130-1ca15d80-3b28-11eb-95bb-3093c13c36ac.png)

**Comment by sharangsamonkar** [comment]
fixed #266 Assigning this issue to qa as well.

**Comment by HazelColaco19** [comment]
fixed
