### ISSUE TITLE
Weekly Staff has a miscalculation

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#248]
Expected Calculation: 

= ( +300+900-500-50 )
= 1200 - 550
=  650

![image](https://user-images.githubusercontent.com/55691499/101644697-87389780-3a5b-11eb-8341-34e6370d0101.png)

**Comment by sharangsamonkar** [comment]
please add some transaction/add attendance so that the salary calculation is re-triggered

**Comment by HazelColaco19** [comment]
Closing this but opening new. Related issue on monthly.
