### ISSUE TITLE
Overtime Pay Accepts non numeric values

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#25]
Overtime Pay Accepts non numeric values
Description:-overtime pay must be numeric but it accepts non numeric characters too.
![2020-10-29 (2)](https://user-images.githubusercontent.com/72379338/97559928-1174f100-1a04-11eb-8409-57f511a92c01.jpg)

**Comment by SumeshAj** [comment]
floating point numbers are not accepted.

**Comment by ShubhamModi004** [comment]
3rd November Build

**Comment by SumeshAj** [comment]
![2020-11-04](https://user-images.githubusercontent.com/72379338/98112273-eee14d00-1ec7-11eb-9e4c-f733a04cbb4d.png)
IT Takes ceiling value.

![2020-11-04 (1)](https://user-images.githubusercontent.com/72379338/98112346-10dacf80-1ec8-11eb-9225-c43ef3b69468.png)

**Comment by HazelColaco19** [comment]
If you add a single " . " and then click save, upon save it shows an unhandled error message.

Can we restrict the user from adding a " . " at the beginning or the end? If not change the message to the following:

" Please enter a valid input "


![image](https://user-images.githubusercontent.com/55691499/99062203-a103cd80-25c8-11eb-8b47-c0aeecb2a363.png)

![image](https://user-images.githubusercontent.com/55691499/99062229-abbe6280-25c8-11eb-9458-87589d3920bf.png)

**Comment by HazelColaco19** [comment]
@sharangsamonkar @ShubhamModi004 

As mentioned above, this should be fixed for two cases. Currently, it's fixed only for one case. 

See the open case: When the digit ends with a decimal


![image](https://user-images.githubusercontent.com/55691499/99500686-b601a780-29a0-11eb-8af4-447a8cbe2feb.png)

![image](https://user-images.githubusercontent.com/55691499/99500723-be59e280-29a0-11eb-8f9c-4c25a9cfad57.png)

**Comment by HazelColaco19** [comment]
Not fixed.

![image](https://user-images.githubusercontent.com/55691499/99630144-5c13e700-2a5f-11eb-8d8f-6d04db3a54f5.png)

**Comment by ShubhamModi004** [comment]
Added an error message you asked for.

**Comment by HazelColaco19** [comment]
fixed

**Comment by ShubhamModi004** [comment]
For the first attempt as mentioned by Sumesh, only numeric values should be allowed. After adding the fix , Sumesh raised an issue saying cannot add a floating point number, on adding the floating point fix. I didn't handle the case where more than one  ' . ' could be added, to solve the issue I checked on what other apps like google pay and  phone pay do, in their case they allow entries like ' .50 ' which was throwing an error  and ' 90. ' was getting accepted but in both the cases the button below was enabled  , but that implementation was wrong as well. So called up @HazelColaco19  and asked her what exactly is required and implemented same.
