### ISSUE TITLE
Cannot view the business number from admin view. Can view it from owners view

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#255]
Admin
![image](https://user-images.githubusercontent.com/55691499/101731984-7b43e880-3ae2-11eb-8a64-24a92486bd49.png)

Owner

![image](https://user-images.githubusercontent.com/55691499/101732014-87c84100-3ae2-11eb-897b-8c8bbba7efaa.png)

**Comment by sharangsamonkar** [comment]
check numbers fron hangouts

**Comment by ShubhamModi004** [comment]
Getting error on fetch profile call.

**Comment by HazelColaco19** [comment]
fixed
