### ISSUE TITLE
Weekly staff: The Earned value by calculation is " - 1400 ", hence it shouldv been denoted in red

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#257]
weekly s:+700
daily salary: +100
outstanding balance:-2000
-------------
present: 2 = +200
paid leave:1 = +100
half day:1 = +50
over time:400
late fine:4hrs = - 50
late finet: -100
---------------
total = 600-2000=-1400

![image](https://user-images.githubusercontent.com/55691499/101753800-1051dc00-3af9-11eb-8863-e115495c9649.png)

**Comment by sharangsamonkar** [comment]
change the sign of earned

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 please assign to qa once the color is corrected on the frontend. Backend changes are done

**Comment by HazelColaco19** [comment]
fixed
