### ISSUE TITLE
The full day/ half day numerals on the over time counter is always set to 4:30/ 9 hrs??? It should be taken from Employee shift duration

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#259]
Business hours = 8 hrs

staff hours = 8 hrs

![image](https://user-images.githubusercontent.com/55691499/101757822-9a9c3f00-3afd-11eb-912a-bc314dcf8c1f.png)

![image](https://user-images.githubusercontent.com/55691499/101757577-527d1c80-3afd-11eb-8324-68e1dd978c01.png)

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 As discussed passing you the shiftHours in the attendance api. Please note this has to be done on both the single staff attendance and the normal page.

**Comment by HazelColaco19** [comment]
fixed
