### ISSUE TITLE
Transaction listing screen: Earned Salary for the time period = payroll salary with statuses +/ - txns 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#260]
**Current issue:** 

Currently, the earned value in the payroll period on txn listing page is also summing up the amount earned in past payrolls.

**Expected:**
The summed up value should be only shown under " to Pay/ To rcv " in Dues screen under " Previous payroll cards section "

![image](https://user-images.githubusercontent.com/55691499/101763660-1948aa80-3b05-11eb-9a08-99ce66d00c9f.png)

![image](https://user-images.githubusercontent.com/55691499/101763706-2a91b700-3b05-11eb-828c-c447d0a6fc6d.png)

**Comment by sharangsamonkar** [comment]
earned should be of the current cycle only

**Comment by sharangsamonkar** [comment]
the amount is changed. please check this only once #257 is assigned to QA by @ShubhamModi004

**Comment by HazelColaco19** [comment]
fixed
