### ISSUE TITLE
If you add another month post clearance of Dues for previous month, the" Clear Due " button should enable 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#262]
**Current Issue:**

If you clear the dues once, you cannot clear the dues again.

Link: https://drive.google.com/file/d/1aV5pPF4h-6Mv7S-WuqOMAIZQ1264tNDo/view?usp=drivesdk

**Case:** 
I can clear the dues for an employee and then add a month in their payroll. I will need the ability to clear dues when this happens

**Comment by sharangsamonkar** [comment]
works fine for me. Looks like you current payments are more than the due hence the button is disabled

**Comment by HazelColaco19** [comment]
cannot replicate
