### ISSUE TITLE
The same payroll repeats for two staff on click of " Add Previous Month "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#264]
Staff: test for delete

![image](https://user-images.githubusercontent.com/55691499/101769978-cb847000-3b0d-11eb-8d99-72c9547f9977.png)

Staff: Georgio Ajency

![image](https://user-images.githubusercontent.com/55691499/101770037-df2fd680-3b0d-11eb-9393-aa0b1685599b.png)

**Comment by sharangsamonkar** [comment]
initially loading 4 and loading 5 after that

**Comment by HazelColaco19** [comment]
Still happens

**Comment by HazelColaco19** [comment]
#274 Similar. Issue to be tracked on #274
