### ISSUE TITLE
The Earned Amount is incorrect for all staff types

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#266]
It reflects correctly on Dues screen - payable value here

![image](https://user-images.githubusercontent.com/55691499/101791299-60e12d80-3b29-11eb-95e8-5fc5ba6d357a.png)

![image](https://user-images.githubusercontent.com/55691499/101791357-70f90d00-3b29-11eb-92a0-3851a1ef7a8e.png)

**Comment by sharangsamonkar** [comment]
similar to #245

**Comment by HazelColaco19** [comment]
fixed
