### ISSUE TITLE
If you have more than 12 months data, and then you traverse back to the months in the past, the ui breaks when you want to come back to current months

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#267]
**Case:**

1. Add months, so you have Dec 2020 dating back to Nov 2019. 
2. Use the back arrow on single staff attendance detailed screen to go back to these months. 
3. When you cross 12 months, and then you try to click on Next arrow it works only to proceed to one month.  the UI breaks ( the next arrow disappears ) when you click on next arrow for the second time.

**Comment by HazelColaco19** [comment]
#271 Related

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 whats the error here? button not showing up doesnt look like a backend issue.

**Comment by HazelColaco19** [comment]
fixed
