### ISSUE TITLE
Salary cycles are repeated again on scrolling for staff that have more than 5 salary cycles.

### ISSUE THREAD

**Issue by sharangsamonkar** [ajency/Dhanda-App#274]
**Steps to replicate:**

1. Dues screen > Add another cycle.
2. Keep adding the cycles without any break, and then scroll the list.

![image](https://user-images.githubusercontent.com/55691499/102064894-deed4f00-3e1d-11eb-9569-ff38fc4925b3.png)

**Comment by HazelColaco19** [comment]
You can now see unique cards, however, two issues have opened now:

1. The cycles on additions take time to add and the screen goes blank for a few seconds.
2. On continuously adding the cycles, newest cycles added cannot be viewed unless you scroll again or go back to staff listing and come again.

Recorded in video:

**Comment by ShubhamModi004** [comment]
@HazelColaco19  

Since adding a cycle makes changes to calculation and UI I am refresh the page the top section will now be visible but the months will reset to 4 and then on scroll loading more .

**Comment by HazelColaco19** [comment]
It is still repeating, lets get on a call. Can you the case. @ShubhamModi004

**Comment by HazelColaco19** [comment]
fixed
