### ISSUE TITLE
Txn listing page > click on presents ( statuses ) > single staff attendance screen > Add Late fine, OT, PL etc > come back to txn listing screen: The added statuses are not reflected on the txn listing screen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#278]
Expected: when you land back on txn listing, the txn shud be reflected. Please add refresh

Currently, it reflects after you go to staff listing/ dues page  and are back to the transaction listing

**Comment by ShubhamModi004** [comment]
@HazelColaco19 

Added late fine , overtime and paid leave and pressed back button could see all the changes reflected on the screen

**Comment by HazelColaco19** [comment]
half-day is still not reflecting

**Comment by HazelColaco19** [comment]
fixed
