### ISSUE TITLE
Salary field: the dots should not get accepted in this field. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#282]

**Comment by HazelColaco19** [comment]
When I enter 1 decimal/ dot, the button goes green. And on click of the continue button the button goes grey. This is incorrect behavior. 
If a single decimal is entered the button should go grey

![image](https://user-images.githubusercontent.com/55691499/102220628-18e65000-3f07-11eb-829c-8683f108d8f6.png)

**Comment by snehaajency** [comment]
issue: noticed when i enter more then one commas,the button turns green.

![Screenshot_2021-01-19-15-50-52-894_com app ogaji test](https://user-images.githubusercontent.com/4660706/105021295-6574fc00-5a6e-11eb-8efa-bf7bd9876701.jpg)
