### ISSUE TITLE
Have the entire row clickable on Staff Listing screen. currently only the name is clickable

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#285]
See marked below:

![image](https://user-images.githubusercontent.com/55691499/102486922-c5533e00-408f-11eb-84bd-2c7fde60553f.png)

**Comment by ShubhamModi004** [comment]
Changed it for staff screen made the the entire cell clickable instead of just the name.

**Comment by HazelColaco19** [comment]
fixed
