### ISSUE TITLE
Change " Sms " to " Whatsapp " in annoted below

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#288]
![image](https://user-images.githubusercontent.com/55691499/102493260-eff5c480-4098-11eb-98e4-5a77fa4f5944.png)

**Comment by ShubhamModi004** [comment]
Changed the text SMS to WhatsApp since the line was pushing the set alarm towards right on my device reduced the text size  from 12 to 11.

**Comment by HazelColaco19** [comment]
see there is space between the  text and checkbox @ShubhamModi004 

![image](https://user-images.githubusercontent.com/55691499/102745370-cc28cc00-4381-11eb-865a-6e051a62ce25.png)

**Comment by HazelColaco19** [comment]
fixed
