### ISSUE TITLE
Strings mismatched with the title of add Note

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#29]
Strings mismatched with the title.
![2020-10-29 (5)](https://user-images.githubusercontent.com/72379338/97562794-35d2cc80-1a08-11eb-8576-8fb713449dbe.jpg)

**Comment by SumeshAj** [comment]
![2020-11-01 (3)](https://user-images.githubusercontent.com/72379338/97839091-7f246400-1d07-11eb-9e08-bcaaf038854e.jpg)

**Comment by HazelColaco19** [comment]
Fixed
