### ISSUE TITLE
If phone font-size is default,then for self-attendence data is getting trimmed.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#292]
**issue**:If phone font-size is default,then for self-attendance data is getting trimmed.

**steps**:Attendance>>Attendance prompt.

image:
![Screenshot_2021-01-07-16-13-46-962_com app ogaji test](https://user-images.githubusercontent.com/4660706/103883910-d548c580-5103-11eb-9b46-e54278c88cde.jpg)

**Comment by HazelColaco19** [comment]
Text changed to  " Attendance Prompt "

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-09-39-47-359_com app ogaji test](https://user-images.githubusercontent.com/4660706/105125934-95221380-5b03-11eb-892c-07d2404499ce.jpg)
fixed.
