### ISSUE TITLE
“30 days every month” box is missing on Add business

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#293]
**issue**:On add business,“30 days every month” box is missing.

design image:
![image](https://user-images.githubusercontent.com/4660706/103889127-e72e6680-510b-11eb-9ae0-214c7b012b32.png)

App: ![Screenshot_2021-01-07-15-57-34-439_com app ogaji test](https://user-images.githubusercontent.com/4660706/103889149-f3b2bf00-510b-11eb-9ac0-b3d5b4728368.jpg)

**Comment by HazelColaco19** [comment]
Closing this. This isn't an issue but the requirement change
