### ISSUE TITLE
on salary payment type,in design the title name is “ select salary payment type” where as in app “select” is not present.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#298]
**issue**:on salary payment type,in design the title name is “ select salary payment type” where as in app “select” is not present.
**expected**: The title should have been select salary payment type.

**Design**:
![image](https://user-images.githubusercontent.com/4660706/104166805-57e1c580-5421-11eb-9789-f40fd0d43a6c.png)

**Development**:
![Screenshot_2021-01-11-15-27-09-866_com app ogaji test](https://user-images.githubusercontent.com/4660706/104166946-924b6280-5421-11eb-9227-da1030d592a2.jpg)

**Comment by ShubhamModi004** [comment]
Some phone text overflows from the screen . So I removed the word select

**Comment by HazelColaco19** [comment]
Can be closed.
