### ISSUE TITLE
The buttons on the verification page have more width.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#299]
**issue**:The buttons are longer in width as compared with design.
**expected**:The button width should be less then the horizontal line below it.

**Design**: 
![image](https://user-images.githubusercontent.com/4660706/104167561-89a75c00-5422-11eb-9eb5-5c2c8266aea7.png)

**Development*:
![Screenshot_2021-01-11-15-34-12-662_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/104167823-05090d80-5423-11eb-8fae-20ee78f4cfae.jpg)

**Comment by HazelColaco19** [comment]
Button sizes need to be aligned with text on top, so design to be ignored. Closing issue
