### ISSUE TITLE
The vertical green bar for the title should have exceeded when the title is of 2 lines.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#302]
**issue**:the vertical green bar is static and is not getting adjusted as the text increases.
**expected**:The vertical green bar for the title should have exceeded when the title is of 2 lines.

![Screenshot_2021-01-11-16-22-03-349_com app ogaji test](https://user-images.githubusercontent.com/4660706/104172220-e9553580-5429-11eb-9e62-0b42ee58740b.jpg)

**Comment by ShubhamModi004** [comment]
As discussed over phone call now the vertical bar is of height 100%
