### ISSUE TITLE
The Month calculation under business payroll is not showing the number of days.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#303]
**issue***:On business page,under business payroll>>month calculation is showing as calendar month.
**expected**:No of days should be mentioned.

**Design**:
![image](https://user-images.githubusercontent.com/4660706/104173188-6a60fc80-542b-11eb-9b57-86f845ff2ada.png).

**Development**:
![Screenshot_2021-01-11-16-38-59-720_com app ogaji test](https://user-images.githubusercontent.com/4660706/104173334-9ed4b880-542b-11eb-9d42-b76339c2e1bc.jpg)

**Comment by HazelColaco19** [comment]
30 days option removed per client feedback, will only show calendar month option. Closing issue
