### ISSUE TITLE
On business page when you edit payroll and change shift hours and save an message gets displayed.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#304]
**issue**:On business page when you edit payroll and change shift hours and save an message gets displayed.
**steps**:Business>>Business payroll>>edit>>change the shift hrs>>save>>continue.

![Screenshot_2021-01-08-12-48-08-924_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/104176498-59b18600-542d-11eb-9b53-e7d8686c02d5.jpg)

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 This thrown when the user token is not passed or is incorrect. Can you please confirm this?

**Comment by ShubhamModi004** [comment]
@sharangsamonkar

on business api call
response that I get is with **phone: null**
{"code": "success", "data": {"admin": [[Object], [Object], [Object]], "businessName": "Mishra peda", "country": null, "currency": "IDR", "owner": "Mishra", "phone": null, "refId": "B21605952398658", "salaryMonthType": "calendar_month", "shiftHours": "08:00:00", "staffTotal": 9}, "message": "success"}


this is the body I am passing
 {"businessName": "Mishra peda", "currency": "IDR", "lang": "en", "phCountryCode": 91, "phone": null, "refId": "B21605952398658", "salaryMonthType": "calendar_month", "shiftHours": "08:00", "timezone": "+05:30"}

**Comment by snehaajency** [comment]
fixed
