### ISSUE TITLE
when you send an invite,in the message admin invited successfully “dukan “ name is mentioned.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#305]
**issue**:when you send an invite,in the message admin invited successfully “dukan “ name is mentioned.
**expected**:the translated name should appear instead of dukhan/dhandha.

![PicsArt_01-11-04 58 44](https://user-images.githubusercontent.com/4660706/104177207-68e50380-542e-11eb-8d96-ba24d6eb1441.jpg)

**Comment by ShubhamModi004** [comment]
Changed Dhanda and dukhan word to Ogaji wherever used

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-10-12-34-224_com app ogaji test](https://user-images.githubusercontent.com/4660706/105128113-5f335e00-5b08-11eb-9115-de8f8ce5880e.jpg)
fixed
