### ISSUE TITLE
Issues on Add Work Page

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#308]
**issues**: 

On add work page 

1. According to design there should be "add work" below the name, which in the application is replaced with a number.
2. Enter details or select from drop-down placeholder could have less font size so that the whole sentence is visible.
3. Enter details or select from drop-down does not have a drop-down arrow.
4. Rate per unit field is not working.
5. If you type anything in "enter details or select from drop-down", you can see only white space below as you type.

**Development**:
![Screenshot_2021-01-13-14-54-39-586_com app ogaji test](https://user-images.githubusercontent.com/4660706/104432990-94dbc280-55af-11eb-8863-6f1165be51d8.jpg)

**design**:
![image](https://user-images.githubusercontent.com/4660706/104433073-ab821980-55af-11eb-96ac-55243331def1.png)

**Comment by HazelColaco19** [comment]
@ShubhamModi004 @snehaajency 

1 -  can be ignored since in previous staff types we have staff name and number under it.
2 -  Add this placeholder text, " Start typing to select the task details "
3 -  can be ignored. not an issue
4 -  can be ignored. not an issue
5 - Can be ignored.

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-11-34-08-424_com app ogaji test](https://user-images.githubusercontent.com/4660706/105133912-8c393e00-5b13-11eb-9f02-152cfcd45b91.jpg)
fixed
