### ISSUE TITLE
The date looks different as compared to design,the search icon and 3 dots besides it is missing

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#309]
**issue** 1.The date looks different as compared to design.In design it is 04 jan'21 and in app it is 04 jan 21.
               2.The search icon and 3 dots besides it is missing
**expected**: should have been 04 jan'21 according to design.
            2.should have a search icon and 3 dots.

**design**:
![image](https://user-images.githubusercontent.com/4660706/104434041-c608c280-55b0-11eb-9d1c-1d6caab58fe9.png)

**development**:
![Screenshot_2021-01-13-15-04-31-792_com app ogaji test](https://user-images.githubusercontent.com/4660706/104434133-dfaa0a00-55b0-11eb-9814-49bfe1d48bc1.jpg)

**Comment by HazelColaco19** [comment]
Can be closed. Requirement change
