### ISSUE TITLE
Under present when number of days is 1 then it should be "1day",colans are missing after salary.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#311]
**issue**:1.Under present it is 1 days instead of 1 day.
                2. colan is missing after "salary(monthly)
**expected**:1.It should be singular.(1 day)
                2. expected a colan according to design.

**image**:
![Screenshot_2021-01-13-15-04-31-792_com app ogaji test](https://user-images.githubusercontent.com/4660706/104435938-fe110500-55b2-11eb-827e-293cfc3022dc.jpg)

![image](https://user-images.githubusercontent.com/4660706/104436246-6233c900-55b3-11eb-855e-95d93e3b33da.png)

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Ignore the Colan, it looks better without. Please fix " 1 day "/  " 2 days " issue

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-10-27-15-120_com app ogaji test](https://user-images.githubusercontent.com/4660706/105129022-3318dc80-5b0a-11eb-8731-8b5137dafa81.jpg)
fixed
