### ISSUE TITLE
switch the language to bahasa>>procced to verification>>On the first line the number is missing only + can be seen.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#313]
**issue**:switch the language to bahasa, 1.on proceed to verification page,the first line is "T continue with otp verification on +". the phone number is not visible.

2.on change number page,the above issue is seen again on last line

**expected**:phone number should be visible.
**image**:
![Screenshot_2021-01-13-18-11-19-681_com app ogaji test](https://user-images.githubusercontent.com/4660706/104454649-307b2c00-55cc-11eb-8b63-0b7d83738639.jpg)
![Screenshot_2021-01-13-18-11-28-497_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/104454657-34a74980-55cc-11eb-97c7-908bc9bea165.jpg)

**Comment by ShubhamModi004** [comment]
Could not replicate the same I think steps to replicate same would be different

**Comment by snehaajency** [comment]
@ShubhamModi004 issue was seen on earlier version,does not replicate on new version of app hence closing the ticket.
