### ISSUE TITLE
when you add business,type your mobile number after you finish typing it takes you directly to login page.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#314]
**issue**:when you add business,type your mobile number after you finish typing it takes you directly to login page.
**steps**:Add your business>>mobile number>>type the number continuously>> it takes you to login page.

please refer below video:
https://drive.google.com/drive/folders/1jARO0ghNTHkeAkwODWER_L-ECMeXwqGM

**Comment by HazelColaco19** [comment]
@snehaajency Can you test by entering a number " 1212121212 ". Possibility of the issue occurring is due to a click on " login " button, when you try to add the number and keyboard closes automatically after 10 digits.

**Comment by snehaajency** [comment]
closing this issue as could not replicate it.
