### ISSUE TITLE
On successfully adding the work it shows a message "save success",should have been "saved successfully",when you add rates succesfully,it shwows "save rate sucessful"

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#317]
**issue**:1.On successfully adding the work it shows a message "save success".
                2.when you add rates succesfully,it shwows "save rate sucessful"
**expected**:1.should have been "saved successfully".
                  2.should be "saved rate successfully"
![Screenshot_2021-01-15-14-41-40-827_com app ogaji test](https://user-images.githubusercontent.com/4660706/104708382-a524a680-5743-11eb-9b93-c9a9af078b4d.jpg)
![Screenshot_2021-01-15-15-18-07-746_com app ogaji test](https://user-images.githubusercontent.com/4660706/104709820-5b3cc000-5745-11eb-9c82-8cddbdde3dca.jpg)

**Comment by ShubhamModi004** [comment]
Implementation
1) Adding a work I show a message now saved successfully 
2) Adding a rate I show a message saved rate successfully

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-10-36-58-797_com app ogaji test](https://user-images.githubusercontent.com/4660706/105129698-a5d68780-5b0b-11eb-908a-d00853dc9ed2.jpg)
![Screenshot_2021-01-20-10-37-24-876_com app ogaji test](https://user-images.githubusercontent.com/4660706/105129713-acfd9580-5b0b-11eb-8e10-80a3c71b7fbd.jpg)
fixed
