### ISSUE TITLE
on manage work rates page,Noticed there is a underscore in middle of the sentence

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#318]
**issue**:Noticed there is a underscore in middle of the sentence
**expected**:underscore was not needed.
![Screenshot_2021-01-15-15-12-42-349_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/104709108-87a40c80-5744-11eb-8612-861c4eba9c6c.jpg)

**Comment by ShubhamModi004** [comment]
Removed the _ from the text

**Comment by snehaajency** [comment]
![Screenshot_2021-01-20-10-41-31-161_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/105130215-9c015400-5b0c-11eb-8276-2d93ffefdece.jpg)
fixed
