### ISSUE TITLE
Work Basis employee edit: On click of edit of " Staff Info ", and click of Continue on page 1, then on click of device  " back " - the user is landed on Staff listing page and not employee edit page

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#319]
**See Video for steps:**  https://drive.google.com/file/d/1rGZY2Oalvo9T8_I2nfRg-xliZRRy6ILj/view?usp=drivesdk

**Comment by ShubhamModi004** [comment]
On Edit of staff info and click of Continue on page 1 , then click of device back now takes to staff info page

**Comment by snehaajency** [comment]
fixed
