### ISSUE TITLE
WB: Miscalculation of Payable amount 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#320]
**Issue description with steps:**

1. consider a payroll cycle, with payout date as 2nd of the month
2. Add Work on the 15th of the month. This txn should be displayed in the current payroll
3. In dues screen, you will notice the " added work " for 13 Jan is displayed in " dues up to 1 Jan "
4. Expected 1: This figure should been shown under current dues section " current Payable "

See record dated in current payroll cycle, Test design rate

![image](https://user-images.githubusercontent.com/55691499/104736924-a10b7f80-5769-11eb-93a9-688e1c1a500f.png)

See the payable values and date

![image](https://user-images.githubusercontent.com/55691499/104737051-c6988900-5769-11eb-9128-7d46068af9a8.png)

**Comment by snehaajency** [comment]
fixed
