### ISSUE TITLE
Work could be added in days where payroll cycle doesnt exist

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#322]
**Case:**
Payroll cycle exists from Oct 2020 - January 2021
Work was added for the date " 17 April 2020 "

Expected: If the payroll cycle doesn't exist, then the date should not appear in the calendar

![image](https://user-images.githubusercontent.com/55691499/104737932-e3818c00-576a-11eb-98b0-b83fda4fc228.png)

**Comment by sharangsamonkar** [comment]
@HazelColaco19 Shouldn't we allow to add the work for a previous day?

What should happen is once the work has been added in April, the payroll cycle of all the cycles from April to Oct will show up.

The problem with the above approach is that we will be forcing the user to add cycles before he adds work. Thoughts?

**Comment by HazelColaco19** [comment]
Agreed approach: Work can be added in past months, however card creation of months between newly created work and latest month in cycle should be created when work is added in past.

**Comment by snehaajency** [comment]
fixed
