### ISSUE TITLE
Hardcoded values in dues screen ( Total units and To pay )

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#323]
Case: There are no transactions or work records in any of these cycles, however, the To pay value is seen populated 

![image](https://user-images.githubusercontent.com/55691499/104738832-06f90680-576c-11eb-840e-988444fe8b99.png)

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 Please use the totalUnits key for this.

**Comment by snehaajency** [comment]
![Screenshot_2021-02-04-18-03-11-189_com app ogaji test](https://user-images.githubusercontent.com/4660706/106893283-5602dd80-6713-11eb-85ea-3a4e84cfb178.jpg)
fixed
