### ISSUE TITLE
The dark green vertical bar should have the same height as the header layer beneath it.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#324]
The dark green vertical bar should have the same height as the header layer beneath it.

This can be seen throughout the app, please fix all such green bars.

![image](https://user-images.githubusercontent.com/55691499/104740056-7c190b80-576d-11eb-87ad-f89f26772f9a.png)

**Comment by ShubhamModi004** [comment]
This is not a bug its a new task since the old design figma shows same. 
As mentioned adding the height to be same a background beneath.

**Comment by HazelColaco19** [comment]
It is not looking good with 100% height boost. Can we revert it back? @ShubhamModi004 

@snehaajency Please check this once done.

**Comment by snehaajency** [comment]
![Screenshot_2021-02-04-17-48-24-251_com app ogaji test (1)](https://user-images.githubusercontent.com/4660706/106892575-41721580-6712-11eb-8bc8-54cebb6e4fc5.jpg)
