### ISSUE TITLE
WB:when you add a workrate and save it successfully,it shows add rate page for 2 seconds while saving

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#325]
**issue**:when you add a workrate and save it successfully,it shows add rate page for 2 seconds while saving
**expected**:add rate page should not appear
**steps**:Add work>>rates>>add rates>>enter work detail and rate per unit>>save rate.

please refer the video:
https://drive.google.com/drive/folders/1TtjE95aZ0QD6jreiXFWiE_TzWuK6Tsqk

**Comment by ShubhamModi004** [comment]
It takes time making an api call to backend. Only in case of success I can navigate the user back and in case on an error I need to show an error. Hence we need to wait there

**Comment by snehaajency** [comment]
fixed
