### ISSUE TITLE
App doesnot work when there is low connectivity or no internet,there is no app icon in drawer.

### ISSUE THREAD

**Issue by snehaajency** [ajency/Dhanda-App#326]
issue seen on test case 7,8,19.
App doesnot work when there is low connectivity or no internet,there is no app icon in drawer.
Below is the link to the testcases
https://docs.google.com/spreadsheets/d/1jiUx9yt7wiUzYHrGKq4wSQpPNEtqPzgh54lyIglymvA/edit#gid=0

**Comment by HazelColaco19** [comment]
Can be ignored
