### ISSUE TITLE
Timezone field in the businesses  table is not getting populated.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#33]
when we add business  the "timezone" field is not  getting populated.
![Screenshot (55)](https://user-images.githubusercontent.com/72379338/97693301-f9b27100-1ac6-11eb-9782-80fb614fad34.png)

**Comment by sharangsamonkar** [comment]
@SumeshAj Can you try again today? We could not replicate this issue. Also please mention which device you are using and the build name that you installed.

**Comment by SumeshAj** [comment]
Time-zone gets populated.
