### ISSUE TITLE
Traverse back thro app not provided for pop ups.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#38]
There is no option provided to traverse back in App other then using mobile back button.
![2020-11-02](https://user-images.githubusercontent.com/72379338/97853417-18f70b80-1d1e-11eb-8188-68ceb0b7af66.jpg)

**Comment by ShubhamModi004** [comment]
If the button to do so is required ill add.

**Comment by SumeshAj** [comment]
yes a button will be better and also if any area above popup is clicked it takes u to previous screen(suggestion).

**Comment by HazelColaco19** [comment]
works
