### ISSUE TITLE
The selection box opacity increases when clicked to Hours penalty.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#42]
The selection box opacity increases when clicked to Hours penalty of Late Fine.

**Comment by sharangsamonkar** [comment]
@Sumesh
Not clear. Can you explain it with a screenshot?

**Comment by SumeshAj** [comment]
![2020-11-03 (4)](https://user-images.githubusercontent.com/72379338/98078999-2258b300-1e99-11eb-8283-5f157a388a48.jpg)
when we click on the bidirectional time selector for me it looked  odd that the opacity increases making it hard to check the selector before releasing the touch.
