### ISSUE TITLE
Start and finish time of hourly staff behaves in unusual manner

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#47]
Start and finish time of hourly staff behaves in unusual manner.
When I select Start time and then select finish time, later I try to edit start time then the finish time changes automatically.

**Comment by ShubhamModi004** [comment]
Start time is allowed to be anything and finish time is supposed to be after the start time, so now I am deleting the finish time directly

**Comment by HazelColaco19** [comment]
So right now, we can enter an end later which is lesser than the start time

![image](https://user-images.githubusercontent.com/55691499/98952580-a1955900-2521-11eb-88f8-2d9cc060772b.png)

**Comment by HazelColaco19** [comment]
fixed
