### ISSUE TITLE
Attendance Landing Page : Shadow cannot be seen below the section with title " Today "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#56]
**Section A.** 
1. The design has a shadow falling beneath the section " today ". In developed there is no shadow effect + the lower section ( which contains the present/ absent status ) has a greyer shade. Check design

**Design:**

![image](https://user-images.githubusercontent.com/55691499/98339162-4c44dd80-2031-11eb-88a1-cf17cb174507.png)

**Developed:**

![image](https://user-images.githubusercontent.com/55691499/98339130-40591b80-2031-11eb-902a-56611d837f74.png)

**Comment by HazelColaco19** [comment]
![image](https://user-images.githubusercontent.com/55691499/99070454-3d809c80-25d6-11eb-91a5-845869e64f20.png)

**Comment by sharangsamonkar** [comment]
@HazelColaco19 : Shadow height needs to increase.

**Comment by HazelColaco19** [comment]
fixed
