### ISSUE TITLE
Attendance Page: Present/ Absent font is incorrect.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#60]
Section C
1. Present/ Absent font is incorrect. It looks bolder in design. Please check if it is Poppins/ Medium

![image](https://user-images.githubusercontent.com/55691499/98340019-b316c680-2032-11eb-8797-d1e73c838bf1.png)

**Comment by ShubhamModi004** [comment]
Took the design from figma. Now it is changed to Lato so made it late

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Always remember the brand font is Poppins. If you see Lato it is a mistake. We tried changing the fonts back for just a few screens, but not possible for all. So during implementation, it should be Poppins. So last time it was Poppins-regular. You had to change it to Poppins-Medium

**Comment by HazelColaco19** [comment]
Fixed
