### ISSUE TITLE
Attendance List view: Late fine should have the currency before the number and overtime should have " hrs " appending the number.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#62]
Section D  
1. Case: Mark employee on " Half Day ", Overtime = 7 Hrs, Add late fine, also add a long note.

a. Question: Late fine should have the currency before the number and overtime should have " hrs " appending the number. @georgioajency 

![image](https://user-images.githubusercontent.com/55691499/98340333-36381c80-2033-11eb-8d88-b85e3e723e55.png)

**Comment by georgio** [comment]
Hey! Looks like you mentioned the wrong person on this issue

**Comment by ShubhamModi004** [comment]
Will discuss

**Comment by sharangsamonkar** [comment]
@HazelColaco19 : As discussed this can be closed since the INR/ hrs will come below the first line
