### ISSUE TITLE
Shift duration pop up : UI issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#69]
6a. The horizontal line above " Save " is a lighter shade on Figma. It is too dark and does not look good.
6b. Also, the " Save " button should have been vertically centered between the line and bottom edge

![image](https://user-images.githubusercontent.com/55691499/98341877-9039e180-2035-11eb-85a9-c3701e44d46e.png)

**Comment by ShubhamModi004** [comment]
Phones with lower pixel density hides the lines if I give it below 1 px. Will try to solve it but 0.2px line mentioned on figma works on new devices and gets hidden on old devices.

**Comment by HazelColaco19** [comment]
Fixed
