### ISSUE TITLE
No categories for DAILY,WORK BASIS,WEEKLY,WORKBASIS

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#7]
There are no categories for DAILY,WORK BASIS,WEEKLY,WORKBASIS

Description-As the staff must be segregated into such category like in case of monthly and hourly staff but the Daily ,weekly and work basis dont have category and are put under one category of monthly
![IMG_20201027_181855](https://user-images.githubusercontent.com/72379338/97303997-27a67400-1881-11eb-9286-31076a92b4e9.jpg)

**Comment by sharangsamonkar** [comment]
I dont think there are sub categories under monthly. Please confirm with the design.
