### ISSUE TITLE
7. Can we reduce the size of all placeholders by one point? currently it looks too big and loud. device one plus 7

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#70]
![image](https://user-images.githubusercontent.com/55691499/98342221-1eae6300-2036-11eb-8155-aa4dcb710adf.png)

**Comment by sharangsamonkar** [comment]
@HazelColaco19 : Reduce by one point. Please share the screenshot with the change. We'll take a call then.

**Comment by HazelColaco19** [comment]
Fixed

**Comment by HazelColaco19** [comment]
@ShubhamModi004  We have to change this for all the placeholders on the app.  You have changed it only on Business page. I had mentioned all placeholders

**Comment by HazelColaco19** [comment]
fixed
