### ISSUE TITLE
Save staff passes 00:00 as the time even though the time is pre populated to 08:00

### ISSUE THREAD

**Issue by sharangsamonkar** [ajency/Dhanda-App#72]
Request object of save staff
Request Body:
{
	"businessRefId": "B801603957526840",
	"refId": "S911603957637198",
	"staffName": "Monthly",
	"countryCode": 1809,
	"phone": "6555555555",
	"salaryType": "monthly",
	"salary": "1000",
	"salaryPayoutDate": 3,
	"dailyShiftDuration": "00:00",
	"currentBalanceType": "no_dues",
	"pendingAmount": ""
}

**Comment by HazelColaco19** [comment]
Sumesh daily - was added as 3:00 hrs.

On the main page, you can see 3 hrs and on the next detailed page you can see defaulted 9 hrs.

![image](https://user-images.githubusercontent.com/55691499/99074399-b3d4cd00-25dd-11eb-8cc8-b8f6d8886924.png)

![image](https://user-images.githubusercontent.com/55691499/99074413-b8998100-25dd-11eb-9297-675c078990ea.png)

**Comment by sharangsamonkar** [comment]
@sharangsamonkar check the single staff api - defaults to business hours

**Comment by sharangsamonkar** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
fixed
