### ISSUE TITLE
Edited staff name not getting updated in the Attendance Page

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#73]
Edited staff name after update is not  getting  reflected.

**Comment by SumeshAj** [comment]
some times the staff is named as test.

**Comment by ShubhamModi004** [comment]
Functionality will change in sprint 3

**Comment by HazelColaco19** [comment]
Cannot update staff @ShubhamModi004 @sharangsamonkar

**Comment by HazelColaco19** [comment]
Fixed
