### ISSUE TITLE
Overtime pop up disappears leaving content on attendance landing page screen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#75]
Steps to replicate:

1. Tap 3 dots
2. Tap Add overtime
3. Press back
4. Tap 3 dots again

![image](https://user-images.githubusercontent.com/55691499/98356796-368fe200-204a-11eb-9e27-b630189a819c.png)

**Comment by ShubhamModi004** [comment]
Cannot replicate the error on my phone

**Comment by sharangsamonkar** [comment]
Try with one hourly and one weekly entry

**Comment by HazelColaco19** [comment]
Fixed
