### ISSUE TITLE
The bottom nav bar ( last logo title is Profile ), not Profile Screen. Also there should be more padding above the icons. looks congested. See design

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#77]
Design:

![image](https://user-images.githubusercontent.com/55691499/98357193-db122400-204a-11eb-8f20-100dcb884040.png)

Developed:

![image](https://user-images.githubusercontent.com/55691499/98357272-fbda7980-204a-11eb-90d8-9f211d9a481d.png)

**Comment by HazelColaco19** [comment]
The padding above and below the icons should be increased. Not fixed

**Comment by HazelColaco19** [comment]
@ShubhamModi004  @ShubhamModi004    padding is still not fixed. There is more space on top. Also, the staff icon is missing a bold line. check design

![image](https://user-images.githubusercontent.com/55691499/99501833-51dfe300-29a2-11eb-8248-9d3274d7ab67.png)

**Comment by ShubhamModi004** [comment]
Can you provide me the staff icons green and gray one in svg formats.

**Comment by HazelColaco19** [comment]
I will send SVG format via email, but here is the link to the icons

Staff grey: https://www.figma.com/file/XoOfwv1zg8xy6ZSgFqY3H2/The-Dhandha-App?node-id=1939%3A220

Staff green: https://www.figma.com/file/XoOfwv1zg8xy6ZSgFqY3H2/The-Dhandha-App?node-id=1939%3A221

**Comment by HazelColaco19** [comment]
Fixed
