### ISSUE TITLE
Error message shown when Editing staff for second time.

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#78]
Error Message shown when i edited staff and later clicked on update staff which had name as just space. second time when i clicked on edit staff it shows me error and i cannot proceed with editing staff.
![2020-11-06](https://user-images.githubusercontent.com/72379338/98357411-2af0eb00-204b-11eb-9f1f-5e3713868228.png)

**Comment by SumeshAj** [comment]
this occurs when the staff is added some previous pending dues

**Comment by ShubhamModi004** [comment]
Functionality changes in sprint 3

**Comment by sharangsamonkar** [comment]
issue was on server side with dues type. fixed and test friday.

**Comment by HazelColaco19** [comment]
Fixed
