### ISSUE TITLE
Highlighting of selection of Attendance  doesnt work for earlier days 

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#8]
Highlighting of selection of Attendance  doesnt work.

Description:-Date once selected of prev day then the currently marked gets highlighted.
Example:If i mark the attendance of daily staff today then the highlighted part which is tick and the Cross ,Now if you Select the prev day then this highlighted mark should appear but the mark appears but nothing gets mentioned on the top bar which states the total attendance.
![PicsArt_10-27-06 28 36](https://user-images.githubusercontent.com/72379338/97305118-b23ba300-1882-11eb-8758-2b2d0333ee2c.jpg)

**Comment by SumeshAj** [comment]
![2020-11-04 (2)](https://user-images.githubusercontent.com/72379338/98114080-bbec8880-1eca-11eb-9bc9-4703e9582538.jpg)

**Comment by HazelColaco19** [comment]
Fixed
