### ISSUE TITLE
You cannot see the records in monthly for any record that is " Present ". You can see it if it's absent, paid leave, holiday

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#88]
https://drive.google.com/file/d/1HTSx3F9EDS5diTZIi32NoMqB-nPkLePB/view?usp=drivesdk

![image](https://user-images.githubusercontent.com/55691499/98676048-14b39980-2381-11eb-81ef-1c80bf307a6a.png)

**Comment by sharangsamonkar** [comment]
Entries when the attendance is not there

**Comment by HazelColaco19** [comment]
Fixed.
