### ISSUE TITLE
If the person is on leave, it should show 0 hours.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#90]
![image](https://user-images.githubusercontent.com/55691499/98676382-8db2f100-2381-11eb-8ec1-57b0e2a5e451.png)

Developed: Can see 8 hrs even when on leave

![image](https://user-images.githubusercontent.com/55691499/98676609-d5397d00-2381-11eb-8156-de5422e20dd3.png)

**Comment by sharangsamonkar** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
This is not an immediate fix. as in when we mark the user as absent from Present, you need to have another action to actually have it appear on the screen

See video:

https://drive.google.com/file/d/1JOLOQoRuRIfwNQlLWYa1M2KhPa_k4WRV/view?usp=drivesdk

**Comment by sharangsamonkar** [comment]
Hours to be updated from the status api response

**Comment by ShubhamModi004** [comment]
Keeping the same functionality as hourly staff. Showing the text the text as Absent instead of time.

**Comment by HazelColaco19** [comment]
shows 0 hours for monthly, weekly types.

For work basis, it shows undefined hours.

![image](https://user-images.githubusercontent.com/55691499/99502374-fa8e4280-29a2-11eb-98cb-1368ab79d940.png)

**Comment by ShubhamModi004** [comment]
What do I show for weekly staff removed the undefined time

**Comment by HazelColaco19** [comment]
The undefined error seems fixed, but can you elaborate on the comment? @ShubhamModi004

**Comment by HazelColaco19** [comment]
Leave it blank. Closing this
