### ISSUE TITLE
The Note is getting cropped too much

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#91]
![image](https://user-images.githubusercontent.com/55691499/98678064-fe5b0d00-2383-11eb-826d-f3d99d74605e.png)

**Comment by HazelColaco19** [comment]
Still the same. Can you increase the trim limit?
![image](https://user-images.githubusercontent.com/55691499/99072694-889cae80-25da-11eb-8b9e-d20dfdc4e768.png)

**Comment by HazelColaco19** [comment]
Can you keep the trim limit to 15 characters inclusive of spaces?

![image](https://user-images.githubusercontent.com/55691499/99502647-61abf700-29a3-11eb-9b5d-192ff2a8a49d.png)

**Comment by ShubhamModi004** [comment]
<img width="369" alt="Screenshot 2020-11-18 at 5 18 46 PM" src="https://user-images.githubusercontent.com/34206153/99527012-20770f80-29c2-11eb-8665-25dd50761103.png">
<img width="384" alt="Screenshot 2020-11-18 at 5 18 36 PM" src="https://user-images.githubusercontent.com/34206153/99527030-279e1d80-29c2-11eb-9464-d1c40425b9bf.png">

Different screen sizes will have different width I Hope this looks better now

**Comment by HazelColaco19** [comment]
It does look way better on One plus. But somehow it is still going under the circle. Can you reduce maybe a lil such that trimmed note doesn't come under the Present circle

![image](https://user-images.githubusercontent.com/55691499/99633301-aa77b480-2a64-11eb-8861-1cff871a825e.png)

**Comment by ShubhamModi004** [comment]
Trying to create an ideal situation on all the phones reduced the width to 3 points

**Comment by HazelColaco19** [comment]
fixed
