### ISSUE TITLE
Business screens: Post inviting an admin the invitation is not reflected on business screen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#96]
**Expected:**

The invited user's name should be reflected in here as shown in the screenshot.

![image](https://user-images.githubusercontent.com/55691499/98946167-8aeb0400-2519-11eb-8b5f-d950ba54c842.png)

**Comment by sharangsamonkar** [comment]
@ShubhamModi004 
Business page needs to update.

**Comment by HazelColaco19** [comment]
fixed
