### ISSUE TITLE
Business Screen: The business owner name cannot be seen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#97]
![image](https://user-images.githubusercontent.com/55691499/98946397-dbfaf800-2519-11eb-95a6-25b16f10f675.png)

**Comment by sharangsamonkar** [comment]
Owner name is optional, hence comes blank.

@HazelColaco19 need confirmation on making the owner name mandatory.

**Comment by HazelColaco19** [comment]
Can we have these changes for the scenario when the Owner name is empty? @sharangsamonkar 

Have the Owner name empty:

![image](https://user-images.githubusercontent.com/55691499/99223487-99cc0200-280a-11eb-83a6-d1754a7e2c62.png)

But have owner tag in list

![image](https://user-images.githubusercontent.com/55691499/99223509-a51f2d80-280a-11eb-8290-c1c050aaec45.png)

**Comment by HazelColaco19** [comment]
Fixed. Raised new issue in #143 . This can be closed
